platform :ios, '9.0'
source 'https://github.com/CocoaPods/specs.git'


use_frameworks!
target 'Chainup' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  pod 'SGPagingView' ,'1.5.3'
  pod 'SnapKit' , '4.0.0'
  pod 'SVProgressHUD', '2.1.2'
  pod 'RxSwift' , '4.2.0'
  pod 'RxCocoa' , '4.2.0'

  pod 'Alamofire' , '4.7.3'
  pod 'YYImage' , '1.0.4'
  pod 'YYText' , '1.0.7'
  pod 'YYWebImage' , '1.0.5'

  pod 'Starscream' , '3.0.5'
  pod 'IQKeyboardManager'
  pod 'DZNEmptyDataSet'
  pod 'MJRefresh', '~> 3.1.15.7'
  pod 'Moya/RxSwift', '~> 12.0'
  pod 'SwiftTheme'
  pod 'MJExtension'
  pod 'AliyunOSSiOS', '~> 2.10.7'

  pod 'SwiftEntryKit', '0.7.2'
  pod 'SKPhotoBrowser', '~> 5.0.0'
  pod 'SwiftyDrop', '~>4.0'
  pod 'URLNavigator'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  pod 'Firebase/Crashlytics'
  pod "dsBridge"
  pod 'FSPagerView'
  pod 'SwiftEventBus','3.0.1'
  
  pod 'Reachability'
  pod 'SocketRocket'


  
 

end
